[package]
name = "rust_simple_redis_module"
version = "0.1.0"
authors = ["umorigu <umorigu@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"
